on:
  workflow_dispatch:
    inputs:
      GHC_GIT_REF:
        description: Commit in GHC repo to build
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          build-args: |
            GHC_GIT_REF=${{ inputs.GHC_GIT_REF }}
            BUILD_ARGS=-j1
          tags: |
            brandonchinn178/ghc-js-backend:latest
            brandonchinn178/ghc-js-backend:${{ inputs.GHC_GIT_REF }}
          platforms: linux/amd64
          push: true
